# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

timezone: "America/Los_Angeles"

# Your application's name
appname: "Family::Site"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
session: "YAML"
session_dir: "/tmp/example_family-sessions"

plugins:
  Database:
        driver: 'mysql'
        database: 'example_family'
        host: 'localhost'
        port: 3306
        username: 'root'
        password: 'abc123'
        connection_check_threshold: 10
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
        log_queries: 1
  DBIC:
    "example_family":
        schema_class: Family::Site::Schema
        dsn: "dbi:mysql:database=example_family"
        user: 'root'
        password: 'abc123'
        options:
            quote_names: 1
  Auth::Extensible:
        exit_page: '/'
        login_page_handler: 'Family::Site::login_page_handler'
        realms:
            users:
                provider: 'Database'
                disable_roles: 1
                users_table: 'user'
                users_id_column: 'id'
                users_username_column: 'username'
                users_password_column: 'password'
